name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    # https://github.com/actions/cache/blob/master/examples.md#go---modules
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: go

    - name: Download Go Modules
      if: steps.cache.outputs.cache-hit != 'true'
      run: go mod download

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

